const { Schema, model } = require("mongoose");

const ListingSchema = new Schema({
  name: String,
  summary: String,
  space: String,
  description: String,
  neighborhood_overview: String,
  notes: String,
  transit: String,
  access: String,
  interaction: String,
  house_rules: String,
  thumbnail_url: String,
  medium_url: String,
  xl_picture_url: String,
  host_id: String,
  host_url: String,
  host_name: String,
  host_since: String,
  host_location: String,
  host_about: String,
  host_response_time: String,
  host_response_rate: Number,
  host_thumbnail_url: String,
  host_picture_url: String,
  host_neighbourhood: String,
  host_listings_count: Number,
  host_total_listings_count: Number,
  host_verifications: {
    email: String,
    phone: Number,
  },
  street: String,
  neighbourhood: String,
  city: String,
  state: String,
  zipcode: String,
  market: String,
  country_code: String,
  country: String,
  property_type: String,
  room_type: String,
  accommodates: Number,
  bathrooms: Number,
  bedrooms: Number,
  beds: Number,
  bed_type: String,
  amenities: [String],
  square_feet: Number,
  price: Number,
  weekly_price: Number,
  monthly_price: Number,
  security_deposit: Number,
  cleaning_fee: Number,
  guests_included: Number,
  extra_people: Number,
  minimum_nights: Number,
  maximum_nights: Number,
  has_availability: Boolean,
  number_of_reviews: Number,
  first_review: String,
  last_review: String,
  review_scores_rating: Number,
  review_scores_accuracy: Number,
  review_scores_cleanliness: Number,
  review_scores_checkin: Number,
  review_scores_communication: Number,
  review_scores_location: Number,
  review_scores_value: Number,
  reviews_per_month: Number,
  features: [String],
});

const Listing = model("Listing", ListingSchema);

module.exports = Listing;
